# Generated by Django 5.2.6 on 2025-11-17 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name with designation (e.g., Dr. M. Saravanakumar, Ph.D.)', max_length=200)),
                ('designation', models.CharField(default='Dean-Regional Campus (Warden)', max_length=200)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dean_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dean_profiles',
            },
        ),
    ]
