# Generated by Django 5.2.8 on 2025-11-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('establishment', 'Establishment'), ('mess', 'Mess')], max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='hostels.hostel')),
            ],
            options={
                'ordering': ['hostel', 'account_type'],
                'unique_together': {('hostel', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='YearlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Academic year (e.g., 1, 2, 3, 4)')),
                ('establishment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mess_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_fees', to='hostels.hostel')),
            ],
            options={
                'ordering': ['hostel', 'year'],
                'unique_together': {('hostel', 'year', 'academic_year')},
            },
        ),
    ]
