# Generated by Django 5.2.8 on 2025-11-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_bankaccount_yearlyfee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearlyfee',
            unique_together={('hostel', 'year')},
        ),
        migrations.RemoveField(
            model_name='yearlyfee',
            name='academic_year',
        ),
    ]
