# Generated by Django 5.2.6 on 2025-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_remove_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='designation',
            field=models.CharField(default='Deputy Warden', max_length=200),
        ),
        migrations.AlterField(
            model_name='warden',
            name='name',
            field=models.CharField(help_text='Full name with designation (e.g., Dr. M. Yuvaraju, Ph.D.)', max_length=200),
        ),
    ]
