# Generated by Django 5.2.8 on 2025-11-17 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('bank_loan', 'Bank Loan'), ('scholarship', 'Scholarship'), ('passport', 'Passport Application'), ('visa', 'Visa Application'), ('identity_proof', 'Identity Proof'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending with Warden'), ('warden_approved', 'Approved by Warden'), ('warden_rejected', 'Rejected by Warden'), ('dean_approved', 'Approved by Dean'), ('dean_rejected', 'Rejected by Dean')], default='pending', max_length=20)),
                ('warden_review_date', models.DateTimeField(blank=True, null=True)),
                ('warden_remarks', models.TextField(blank=True)),
                ('dean_review_date', models.DateTimeField(blank=True, null=True)),
                ('dean_remarks', models.TextField(blank=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('certificate_issued_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='bonafide_certificates/')),
                ('verification_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by_dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='hostels.warden')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_requests', to='students.student')),
            ],
            options={
                'db_table': 'bonafide_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
