# Generated by Django 5.2.6 on 2025-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonafide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafiderequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bonafide_attachments/'),
        ),
    ]
