# Generated by Django 5.2.6 on 2025-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonafide', '0003_bonafidesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafidesettings',
            name='cooldown_period',
            field=models.CharField(choices=[('disabled', 'Disabled (No Cooldown)'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='3_months', help_text='Period after approval before student can reapply', max_length=20),
        ),
    ]
