# Generated by Django 5.2.8 on 2025-11-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('CREATE_USER', 'Create User'), ('CREATE_BONAFIDE_REQUEST', 'Create Bonafide Request'), ('WARDEN_APPROVE', 'Warden Approve'), ('WARDEN_REJECT', 'Warden Reject'), ('DEAN_APPROVE', 'Dean Approve'), ('DEAN_REJECT', 'Dean Reject'), ('DOWNLOAD_BONAFIDE', 'Download Bonafide'), ('CREATE_HOSTEL', 'Create Hostel'), ('UPDATE_HOSTEL', 'Update Hostel'), ('CREATE_WARDEN_PROFILE', 'Create Warden Profile'), ('BULK_STUDENT_UPLOAD', 'Bulk Student Upload')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
